apiVersion: v1 
kind: Pod 
metadata:
  name: pod-config
spec:
  containers:
    - name: nginx
      image: nginx
      env:
        - name: myname
          valueFrom:
            configMapKeyRef:
              name: nginx-config # name of the config map you are referencing to 
              key: name #env.name and config map key name can be different
        - name: location
          valueFrom:
            configMapKeyRef:
              name: nginx-config # name of the config map you are referencing to 
              key: location