apiVersion: v1
kind: Pod
metadata:
  name: limit 
spec:
  containers:
  - name: niginx
    image: nginx
    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"
      limits:
        memory: "100Mi"
        cpu: "120m"
